# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#development:
# adapter: mysql
# database: mlip
# username:root
# password:
# host:localhost
# port:3306

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: igel84_tender82
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: mysql0.locum.ru
  database: igel84_voronez82
  pool: 5
  username: igel84_voronez82
  password: kS1G24If
  socket: /var/run/mysqld/mysqld.sock
